on:
  push:
    branches: [ "main" ]

jobs:
  
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: supercharge/mongodb-github-action@1.10.0
      with:
        mongodb-version: '5.0'
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    #- run: dotnet restore ./Tests
    #- run: dotnet test ./Tests/Tests.fsproj -c Release -p:ParallelizeTestCollections=false
    - run: dotnet publish ./HttpApi -c Release -r linux-x64 -o Published
    - run: zip -r yog-robot.agent.zip ./Published
    - uses: actions/create-release@v1
      if: ${{ ! startsWith(github.ref, 'refs/tags/') }}
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        draft: false
        prerelease: false
      