on:
  push:
    tags:
      - 'v*'

jobs:
  
  build:
    runs-on: ubuntu-latest

    steps:
    # - uses: actions/checkout@v3
    # - uses: supercharge/mongodb-github-action@1.10.0
    #   with:
    #     mongodb-version: '5.0'
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    #- run: dotnet restore ./Tests
    #- run: dotnet test ./Tests/Tests.fsproj -c Release -p:ParallelizeTestCollections=false
    - name: build
      run: dotnet publish ./HttpApi -c Release -r linux-x64 -o Published

    - name: zip
      run: zip -r yog-robot.agent.zip ./Published
    
    - name: release 
      id: release
      uses: actions/create-release@v1
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        draft: false
        prerelease: false

    - name: upload binaries
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.release.outputs.upload_url }}
        asset_path: ./yog-robot.agent.zip
        asset_name: yog-robot.agent.zip
        asset_content_type: application/zip
