name: Release

on:
  push:
    branches: [ "main" ]
    tags:
        - '\d{4}\.\d{2}\.\d{2}(?:.*)?'

jobs:
  
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: supercharge/mongodb-github-action@1.10.0
      with:
        mongodb-version: '5.0'
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - run: dotnet restore ./Tests
    - run: dotnet test ./Tests/Tests.fsproj -c Release
    - run: dotnet publish ./HttpApi -c Release -r debian.8-x64 -o Published
    - run: zip -r yog-robot.agent.zip ./HttpApi/Published
    - uses: actions/create-release@v1
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        draft: false
        prerelease: false
      